### ISSUE TITLE
View zooms out

### ISSUE THREAD

**Issue by foFox** [evgenyneu/ios-imagescroll#1]
The view zooms out on rotation, any way around that issue ?

**Comment by evgenyneu** [comment]
This was done intentionally to show the whole image when orientation changes.

```
- (void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)fromInterfaceOrientation
{
    [self initZoom];
}
```

If you do not want that, you could change the code so that `didRotateFromInterfaceOrientation` calls `initZoom` but without changing the zoom scale. Please note that we still need to recalculate `minimumZoomScale` on orientation change.

Cheers
